Repository TikaelSol/starfinder-field-test, pull requests merged in 2024-08, with the labels that each got.

#49 Add SF2E-specific skill actions
  lang/en.json
  module.json
  scripts/actions/computers/access-infosphere.mjs
  scripts/actions/computers/hack.mjs
  scripts/actions/computers/program.mjs
  scripts/actions/index.mjs
  scripts/actions/piloting/drive.mjs
  scripts/actions/piloting/navigate.mjs
  scripts/actions/piloting/plot-course.mjs
  scripts/actions/piloting/run-over.mjs
  scripts/actions/piloting/stop.mjs
  scripts/actions/piloting/stunt.mjs
  scripts/actions/piloting/take-control.mjs
  scripts/sf2e-playtest.mjs
Labels: PR: Enhancement

#77 Correct description and duration of Analyze Target
  packs/spells/Analyze_Target_soIbLojIZyKRhyA8.json
Labels: PR: Data Update

#78 Add heightening to Pocket Vacuum spell
  packs/spells/Pocket_Vacuum_xLAAjxlVce0zFPMs.json
Labels: PR: Data Update

#80 add Weapon Expertise class feature to Mystic Class
  packs/classes/Mystic_FunBoU8459ZUpR3O.json
Labels: PR: Data Update

#81 Update Missile Launcher action cost
  packs/equipment/Missile_Launcher_mpcNkCf0K3es5uJc.json
Labels: PR: Data Update

#82 add spell variants and roll options to Infusion focus spell
  packs/spells/Infusion_eASNMXfMHlT8HksK.json
Labels: PR: Data Update

#83 Assign armor group and base armors to armors
  packs/equipment/Abadarcorp_Travel_Suit_Cvucu9yIVPQXseZl.json
  packs/equipment/Aegis_Series_jt91TufiUk8EbpHn.json
  packs/equipment/Carbon_Skin_w27SAKP67PcGSim4.json
  packs/equipment/Defiance_Series_9L5EcGgxwYie5D6W.json
  packs/equipment/Defrex_Hide_19hcklZtUvKsVmoO.json
  packs/equipment/Estex_Suit_Vt0uY8idmN7sapv4.json
  packs/equipment/Freebooter_Armor_fDkbtTBKrh5bfQ20.json
  packs/equipment/Hardlight_Series_98ytq6q9eVBeVPtl.json
  packs/equipment/Hidden_Soldier_Armor_s7k5oATrAxPnz8sI.json
  packs/equipment/Kyokor_Plating_TrN6Keb7IiE09lZE.json
  packs/equipment/Microcord_Armor_2v6SFf7pS3DRmwEc.json
  packs/equipment/Quilted_Armor_oEH0PCB3cg1bnKds.json
  packs/equipment/Second_Skin_WRw6hYSOdl2wlByk.json
  packs/equipment/Shotalashu_Armor_TjqRzpHBljeq1c7k.json
  packs/equipment/Skyfire_Armor_XRZEHaueju0A2EMr.json
  packs/equipment/Swarmsuit_SAua60XzCbROYS8D.json
  packs/equipment/Tempweave_l76exA0nX7HN0EEd.json
  packs/equipment/Thinplate_C0xFQHypC4ijJygF.json
  packs/equipment/Veskarium_Imperial_Plate_IAad5pfNIV4ZHI2V.json
Labels: PR: Data Update

#85 brush up Vitality Network Effect
  packs/conditions/Effect__Vitality_Network_R0mn1iC3nYvDVKhd.json
Labels: PR: Data Update

#88 Make spell chips not auto-destroy
  packs/equipment/Spell_Chip__1st_Rank_Spell__bpU5tJ3dATZfDtoK.json
  packs/equipment/Spell_Chip__2nd_Rank_Spell__ikPZaVtxv5w5hFgb.json
  packs/equipment/Spell_Chip__3rd_Rank_Spell__bXVe3cvUp3tLR0aJ.json
  packs/equipment/Spell_Chip__4th_Rank_Spell__Y2futubYHfImes32.json
  packs/equipment/Spell_Chip__5th_Rank_Spell__Yif8kuQ813f6O7Bu.json
  packs/equipment/Spell_Chip__6th_Rank_Spell__2fzswZiAtI3qxrPA.json
  packs/equipment/Spell_Chip__7th_Rank_Spell__qTLS39SYG1GdIZkH.json
  packs/equipment/Spell_Chip__8th_Rank_Spell__JXifR8L1N4PgfTCv.json
  packs/equipment/Spell_Chip__9th_Rank_Spell__9iwK4ChWQJYidek2.json
Labels: PR: Data Update

#90 Add a build script and set license
  .gitignore
  LICENSE
  build.mjs
  package-lock.json
  package.json
Labels: PR: Enhancement

#91 Add critical specialization effects to localization file
  lang/en.json
  module.json
Labels: PR: Data Update

#93 Fix Solar Weapon damage when photon attuned
  packs/conditions/Effect__Solar_Weapon__Twin__IHp2EZvBMcumn6Hf.json
  packs/conditions/Effect__Solar_Weapon_lUZuBzMe0UAllDxX.json
Labels: PR: Data Update

#56 Starfinder 2e Dark Theme Stylesheet
  assets/theme/dark/dark_sidebar_bottom.webp
  assets/theme/dark/dark_sidebar_top.webp
  lang/en.json
  scripts/sf2e-playtest.mjs
  styles/dark.css
Labels: PR: UI/UX

#94 Add note to Graviton-Attuned Solar Weapon Strike
  lang/en.json
  packs/conditions/Effect__Solar_Weapon__Twin__IHp2EZvBMcumn6Hf.json
  packs/conditions/Effect__Solar_Weapon_lUZuBzMe0UAllDxX.json
Labels: PR: Data Update

#97 Fix sidebar hover color for high contrast sheet
  styles/high-contrast.css
Labels: PR: UI/UX

#96 Set trait colors in the chat when using the light theme
  styles/light.css
Labels: PR: UI/UX

#98 Improved readability of versatile damage toggles in high contrast mode
  styles/high-contrast.css
Labels: PR: UI/UX

#104 Fix selectors on Hardlight Handwraps
  packs/equipment/Hardlight_Handwraps__Advanced__DlGIyCIhC93ii9uc.json
  packs/equipment/Hardlight_Handwraps__Elite__yGH1bV7f3gHbS3Hl.json
  packs/equipment/Hardlight_Handwraps__Paragon__gIAhbreDlXKmU7eM.json
  packs/equipment/Hardlight_Handwraps__Superior__wm2YkrI3itaZyJBo.json
  packs/equipment/Hardlight_Handwraps__Tactical__jqtCfqaRw7RvST2C.json
  packs/equipment/Hardlight_Handwraps__Ultimate__jSycxwi6UJepgOGI.json
Labels: PR: Data Update

#103 Fix feat type of augmented body and weapon group of machine gun
  packs/equipment/Machine_Gun_ueUgtt9OM3ay3yCT.json
  packs/feats/Augmented_Body_FceVOOFha1gbd95w.json
Labels: PR: Data Update

#102 Apply trait style to item and chat for all styles
  styles/high-contrast.css
  styles/light.css
Labels: PR: UI/UX

#101 Add basic extract packs scripts
  extract-packs.mjs
  package.json
Labels: enhancement

#108 Fix typo in Brutal Anatomy REs
  packs/feats/Brutal_Anatomy_64hqNZ7cAdUMKEJK.json
Labels: PR: Data Update

#109 correct action cost for Get Down and Warning Spray feats
  packs/feats/Get_Down__xI0EGnLqwXJBleTF.json
  packs/feats/Warning_Spray_MXahw1PJeKADO223.json
Labels: PR: Data Update

#112 Add mental immunity to Repair Drone (Playtest Scenario #1)
  packs/creatures/Repair_Drone_QaeFn9B6sgpkuh2g.json
Labels: PR: Data Update

#113 Fix solar weapon predicates
  packs/class-features/Solarian_Weapon_Expertise_npH7KNDEKog5ZALV.json
  packs/conditions/Effect__Solar_Weapon__Twin__IHp2EZvBMcumn6Hf.json
  packs/conditions/Effect__Solar_Weapon_lUZuBzMe0UAllDxX.json
Labels: PR: Data Update
