Repository TikaelSol/starfinder-field-test, pull requests merged in 2024-09, with the labels that each got.

#115 Add link script
  README.md
  link.mjs
  package-lock.json
  package.json
Labels: PR: Enhancement

#117 Dark Theme
  assets/theme/dark/blue-gradient.webp
  assets/theme/dark/primary-shield.svg
  assets/theme/dark/secondary-attribute.svg
  assets/theme/dark/tertiary-shield.svg
  lang/en.json
  styles/dark.css
Labels: PR: UI/UX

#118 Change Fabricator to a Skill Feat as intended
  packs/feats/Fabricator_5qfJ8RzeTe5ucjf1.json
Labels: PR: Data Update

#119 Fix Grenade Launcher
  packs/equipment/Grenade_Launcher_LyLkKttGATjo4wIs.json
Labels: PR: Data Update

#120 Update content to second round of errata
  lang/en.json
  packs/ancestries/Barathu_Kc7Uag3blYKJSUyC.json
  packs/class-features/Ghost_9YYpW8GzNL5E4GXO.json
  packs/class-features/Sniper_WCbFOSycmBVHQfnN.json
  packs/classes/Mystic_FunBoU8459ZUpR3O.json
  packs/classes/Witchwarper_lyPoetdmvTRyjsSM.json
  packs/conditions/Suppressed_enA7BxAjBb7ns1iF.json
  packs/equipment/Bone_Scepter_vOo0Lsd3XeYmgsxl.json
  packs/equipment/Magazine__Magnetar_Rifle__85N7dCTQ45iNBvLA.json
  packs/equipment/Magazine__Seeker_Rifle__amPzF2n4jJMk08Fg.json
  packs/equipment/Mobile_Bulwark_kKWEA9qJYQikFV8M.json
  packs/equipment/Moodskin_yr7MpJwceskjf46w.json
  packs/equipment/Painglaive_96PAkEGmFFPDcks1.json
  packs/equipment/Projectile_Ammo_7P8DldsTekjQGQam.json
  packs/equipment/Screamer_9AZcdcSNdmAD684T.json
  packs/equipment/Sniper_s_Scope_M9vZjxXVI5hC2eRK.json
  packs/feats/Double_Draw_rTuvqumTopTiNOka.json
  packs/feats/Offensive_Defense_LIdBfbzuXU9414al.json
  packs/feats/Tinkering_Fingers_OKHUH2HNLf3yOa3P.json
  packs/feats/Viscious_Incisors__Starfinder__ajOMtadFs1yQfQxL.json
  packs/feats/Whirling_Swipe_UaPlODUZfD3ulWc3.json
  packs/spells/Carcinization_jgsn3NldMCCx66YS.json
  packs/spells/Selective_Invisibility_qRKiadf7GqgxPDaN.json
  packs/spells/Share_Pain_7GPrc67AdaJFAFWm.json
Labels: PR: Data Update

#121 Update action cost of Stunt
  packs/actions/Stunt_ailFBRjKuGCOAsCR.json
Labels: PR: Data Update

#122 Enable dark mode usage
  module.json
  scripts/sf2e-playtest.mjs
Labels: PR: UI/UX

#126 Add Motivating Ring Tone spell effect link to spell
  packs/spells/Motivating_Ringtone_jCr8Airvs1u5D1yR.json
Labels: PR: Data Update

#127 Add spell effect to Detect Thoughts
  packs/conditions/Spell_Effect__Detect_Thoughts_F6GYZA5UwDN5zusb.json
  packs/spells/Detect_Thoughts_tFsq726ZjUDAzML0.json
Labels: PR: Data Update

#128 Fix typos in Advanced Epiphany localization keys
  lang/en.json
Labels: PR: Data Update

#132 Fix spelling of "Everwhelp"
  packs/heritages/Everwhelp_Skittermander_tiMFTIKSh7DP9ezH.json
  packs/journals/Ancestries_q5yEIEjKvnVkwxod.json
Labels: PR: Data Update

#133 Remove "Lashunta" language
  module.json
Labels: PR: Data Update

#134 Add traits to Skittermander ancestry
  .editorconfig
  packs/ancestries/Skittermander_vThlxRrOZfBPDHrO.json
Labels: PR: Data Update

#135 Add action cost to Implant Data spell
  packs/spells/Implant_Data_BmCv54hcNK6rA4q1.json
Labels: PR: Data Update

#138 Fix price of magazines
  packs/equipment/Magazine__Acid_Dart_Rifle__5BQwBIfUaSvbbY1H.json
  packs/equipment/Magazine__Assassin_Rifle__DRAOdODnJl9KREKT.json
  packs/equipment/Magazine__Autotarget_Rifle__dXcNbIh5SaF3w8dW.json
  packs/equipment/Magazine__Breaching_Gun__zTrz5uJJzwh64kje.json
  packs/equipment/Magazine__Card_Slinger__6SBMOr1uM8oMlg7y.json
  packs/equipment/Magazine__Crossbolter__JVUtVlCIkSCKG9Pt.json
  packs/equipment/Magazine__Gyrojet_Pistol__2aU7LtMLAGwGs5PN.json
  packs/equipment/Magazine__Injection_Rifle__qafoMgEmGjymuHMY.json
  packs/equipment/Magazine__Machine_Gun__eIZRl7uImsG9IUyr.json
  packs/equipment/Magazine__Magnetar_Rifle__85N7dCTQ45iNBvLA.json
  packs/equipment/Magazine__Needler_Pistol__0yQOOAZ1d7H6cX89.json
  packs/equipment/Magazine__Reaction_Breacher__jUOL7ocfoIJDSrqX.json
  packs/equipment/Magazine__Scattergun__gNyUDoFyRX2lxFfK.json
  packs/equipment/Magazine__Seeker_Rifle__amPzF2n4jJMk08Fg.json
  packs/equipment/Magazine__Semi_Auto_Pistol__tWFVW7j15qczONKh.json
  packs/equipment/Magazine__Shirren_eye_Rifle__gnXnSJTkdHx05qAF.json
  packs/equipment/Magazine__Stellar_Cannon__h84Ku4giLBWpChtc.json
Labels: PR: Data Update
